// Code generated by protoc-gen-go. DO NOT EDIT.
// source: LiveProto.proto

package live

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateRoomParamVO struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoomParamVO) Reset()         { *m = CreateRoomParamVO{} }
func (m *CreateRoomParamVO) String() string { return proto.CompactTextString(m) }
func (*CreateRoomParamVO) ProtoMessage()    {}
func (*CreateRoomParamVO) Descriptor() ([]byte, []int) {
	return fileDescriptor_18bf21152fb80cf6, []int{0}
}

func (m *CreateRoomParamVO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoomParamVO.Unmarshal(m, b)
}
func (m *CreateRoomParamVO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoomParamVO.Marshal(b, m, deterministic)
}
func (m *CreateRoomParamVO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoomParamVO.Merge(m, src)
}
func (m *CreateRoomParamVO) XXX_Size() int {
	return xxx_messageInfo_CreateRoomParamVO.Size(m)
}
func (m *CreateRoomParamVO) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoomParamVO.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoomParamVO proto.InternalMessageInfo

type ParamVO struct {
	Token     string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Os        string `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Version   int32  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Channelid string `protobuf:"bytes,4,opt,name=channelid,proto3" json:"channelid,omitempty"`
	Pkg       string `protobuf:"bytes,5,opt,name=pkg,proto3" json:"pkg,omitempty"`
	Event     int32  `protobuf:"varint,6,opt,name=event,proto3" json:"event,omitempty"`
	MsgId     string `protobuf:"bytes,7,opt,name=msgId,proto3" json:"msgId,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*ParamVO_CreateRoom
	Data                 isParamVO_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ParamVO) Reset()         { *m = ParamVO{} }
func (m *ParamVO) String() string { return proto.CompactTextString(m) }
func (*ParamVO) ProtoMessage()    {}
func (*ParamVO) Descriptor() ([]byte, []int) {
	return fileDescriptor_18bf21152fb80cf6, []int{1}
}

func (m *ParamVO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParamVO.Unmarshal(m, b)
}
func (m *ParamVO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParamVO.Marshal(b, m, deterministic)
}
func (m *ParamVO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParamVO.Merge(m, src)
}
func (m *ParamVO) XXX_Size() int {
	return xxx_messageInfo_ParamVO.Size(m)
}
func (m *ParamVO) XXX_DiscardUnknown() {
	xxx_messageInfo_ParamVO.DiscardUnknown(m)
}

var xxx_messageInfo_ParamVO proto.InternalMessageInfo

func (m *ParamVO) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ParamVO) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *ParamVO) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ParamVO) GetChannelid() string {
	if m != nil {
		return m.Channelid
	}
	return ""
}

func (m *ParamVO) GetPkg() string {
	if m != nil {
		return m.Pkg
	}
	return ""
}

func (m *ParamVO) GetEvent() int32 {
	if m != nil {
		return m.Event
	}
	return 0
}

func (m *ParamVO) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

type isParamVO_Data interface {
	isParamVO_Data()
}

type ParamVO_CreateRoom struct {
	CreateRoom *CreateRoomParamVO `protobuf:"bytes,8,opt,name=createRoom,proto3,oneof"`
}

func (*ParamVO_CreateRoom) isParamVO_Data() {}

func (m *ParamVO) GetData() isParamVO_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ParamVO) GetCreateRoom() *CreateRoomParamVO {
	if x, ok := m.GetData().(*ParamVO_CreateRoom); ok {
		return x.CreateRoom
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ParamVO) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ParamVO_CreateRoom)(nil),
	}
}

type CreateRoomResultVO struct {
	RoomId               string   `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	RoomNo               int64    `protobuf:"varint,2,opt,name=roomNo,proto3" json:"roomNo,omitempty"`
	AnchorId             string   `protobuf:"bytes,3,opt,name=anchorId,proto3" json:"anchorId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoomResultVO) Reset()         { *m = CreateRoomResultVO{} }
func (m *CreateRoomResultVO) String() string { return proto.CompactTextString(m) }
func (*CreateRoomResultVO) ProtoMessage()    {}
func (*CreateRoomResultVO) Descriptor() ([]byte, []int) {
	return fileDescriptor_18bf21152fb80cf6, []int{2}
}

func (m *CreateRoomResultVO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoomResultVO.Unmarshal(m, b)
}
func (m *CreateRoomResultVO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoomResultVO.Marshal(b, m, deterministic)
}
func (m *CreateRoomResultVO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoomResultVO.Merge(m, src)
}
func (m *CreateRoomResultVO) XXX_Size() int {
	return xxx_messageInfo_CreateRoomResultVO.Size(m)
}
func (m *CreateRoomResultVO) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoomResultVO.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoomResultVO proto.InternalMessageInfo

func (m *CreateRoomResultVO) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *CreateRoomResultVO) GetRoomNo() int64 {
	if m != nil {
		return m.RoomNo
	}
	return 0
}

func (m *CreateRoomResultVO) GetAnchorId() string {
	if m != nil {
		return m.AnchorId
	}
	return ""
}

type ResultVO struct {
	Code  int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg   string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Event int32  `protobuf:"varint,3,opt,name=event,proto3" json:"event,omitempty"`
	MsgId string `protobuf:"bytes,4,opt,name=msgId,proto3" json:"msgId,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*ResultVO_CreateRoom
	Data                 isResultVO_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ResultVO) Reset()         { *m = ResultVO{} }
func (m *ResultVO) String() string { return proto.CompactTextString(m) }
func (*ResultVO) ProtoMessage()    {}
func (*ResultVO) Descriptor() ([]byte, []int) {
	return fileDescriptor_18bf21152fb80cf6, []int{3}
}

func (m *ResultVO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultVO.Unmarshal(m, b)
}
func (m *ResultVO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultVO.Marshal(b, m, deterministic)
}
func (m *ResultVO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultVO.Merge(m, src)
}
func (m *ResultVO) XXX_Size() int {
	return xxx_messageInfo_ResultVO.Size(m)
}
func (m *ResultVO) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultVO.DiscardUnknown(m)
}

var xxx_messageInfo_ResultVO proto.InternalMessageInfo

func (m *ResultVO) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResultVO) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ResultVO) GetEvent() int32 {
	if m != nil {
		return m.Event
	}
	return 0
}

func (m *ResultVO) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

type isResultVO_Data interface {
	isResultVO_Data()
}

type ResultVO_CreateRoom struct {
	CreateRoom *CreateRoomResultVO `protobuf:"bytes,5,opt,name=createRoom,proto3,oneof"`
}

func (*ResultVO_CreateRoom) isResultVO_Data() {}

func (m *ResultVO) GetData() isResultVO_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ResultVO) GetCreateRoom() *CreateRoomResultVO {
	if x, ok := m.GetData().(*ResultVO_CreateRoom); ok {
		return x.CreateRoom
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ResultVO) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ResultVO_CreateRoom)(nil),
	}
}

func init() {
	proto.RegisterType((*CreateRoomParamVO)(nil), "CreateRoomParamVO")
	proto.RegisterType((*ParamVO)(nil), "ParamVO")
	proto.RegisterType((*CreateRoomResultVO)(nil), "CreateRoomResultVO")
	proto.RegisterType((*ResultVO)(nil), "ResultVO")
}

func init() { proto.RegisterFile("LiveProto.proto", fileDescriptor_18bf21152fb80cf6) }

var fileDescriptor_18bf21152fb80cf6 = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x3d, 0x6f, 0xc2, 0x30,
	0x10, 0x86, 0x1b, 0xf2, 0x01, 0xb9, 0x4a, 0xfd, 0x30, 0x55, 0x65, 0x55, 0x1d, 0x50, 0x26, 0x86,
	0x2a, 0x43, 0x3f, 0x86, 0xae, 0x74, 0x29, 0x52, 0x55, 0x90, 0x07, 0xe6, 0x86, 0xc4, 0x40, 0x44,
	0xec, 0x43, 0xb6, 0x89, 0xd4, 0xdf, 0xd2, 0x9f, 0xd7, 0x3f, 0x52, 0xc5, 0x09, 0x81, 0x0a, 0x16,
	0xeb, 0x7d, 0x5f, 0x9d, 0xcf, 0xf7, 0x58, 0x07, 0x97, 0x1f, 0x79, 0xc9, 0xa7, 0x0a, 0x0d, 0xc6,
	0x9b, 0xea, 0x8c, 0xfa, 0x70, 0xfd, 0xa6, 0x78, 0x62, 0x38, 0x43, 0x14, 0xd3, 0x44, 0x25, 0x62,
	0x36, 0x89, 0x7e, 0x1d, 0xe8, 0x36, 0x9a, 0xdc, 0x80, 0x6f, 0x70, 0xcd, 0x25, 0x75, 0x06, 0xce,
	0x30, 0x64, 0xb5, 0x21, 0x17, 0xd0, 0x41, 0x4d, 0x3b, 0x36, 0xea, 0xa0, 0x26, 0x14, 0xba, 0x25,
	0x57, 0x3a, 0x47, 0x49, 0xdd, 0x81, 0x33, 0xf4, 0xd9, 0xce, 0x92, 0x7b, 0x08, 0xd3, 0x55, 0x22,
	0x25, 0x2f, 0xf2, 0x8c, 0x7a, 0xf6, 0xc2, 0x3e, 0x20, 0x57, 0xe0, 0x6e, 0xd6, 0x4b, 0xea, 0xdb,
	0xbc, 0x92, 0xd5, 0x7b, 0xbc, 0xe4, 0xd2, 0xd0, 0xc0, 0xf6, 0xa9, 0x4d, 0x95, 0x0a, 0xbd, 0x1c,
	0x67, 0xb4, 0x5b, 0x4f, 0x61, 0x0d, 0x79, 0x06, 0x48, 0xdb, 0xe1, 0x69, 0x6f, 0xe0, 0x0c, 0xcf,
	0x1f, 0x49, 0x7c, 0xc4, 0xf3, 0x7e, 0xc6, 0x0e, 0xea, 0x46, 0x01, 0x78, 0x59, 0x62, 0x92, 0xe8,
	0x0b, 0xc8, 0xbe, 0x94, 0x71, 0xbd, 0x2d, 0xcc, 0x6c, 0x42, 0x6e, 0x21, 0x50, 0x88, 0x62, 0x9c,
	0x35, 0xc0, 0x8d, 0xdb, 0xe5, 0x9f, 0x68, 0xa9, 0x5d, 0xd6, 0x38, 0x72, 0x07, 0xbd, 0x44, 0xa6,
	0x2b, 0x54, 0xe3, 0xcc, 0xa2, 0x87, 0xac, 0xf5, 0xd1, 0x8f, 0x03, 0xbd, 0xb6, 0x31, 0x01, 0x2f,
	0xc5, 0x8c, 0xdb, 0xb6, 0x3e, 0xb3, 0xba, 0xc2, 0x17, 0x7a, 0xd9, 0xfc, 0x63, 0x25, 0xf7, 0xf8,
	0xee, 0x49, 0x7c, 0xef, 0x10, 0xff, 0xe5, 0x1f, 0xbe, 0x6f, 0xf1, 0xfb, 0xf1, 0x31, 0xd3, 0x69,
	0xfe, 0xd1, 0x2b, 0x3c, 0xa4, 0x28, 0x62, 0x9d, 0x8b, 0xad, 0x4e, 0x31, 0xce, 0x54, 0xbe, 0x30,
	0x73, 0x34, 0xa6, 0xe0, 0x71, 0x91, 0x97, 0x3c, 0xe6, 0xd2, 0xe4, 0xe6, 0xbb, 0xde, 0x93, 0xf9,
	0x76, 0x31, 0x0a, 0xdb, 0xdd, 0x99, 0x07, 0x36, 0x7c, 0xfa, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x9c,
	0xb6, 0xc7, 0xa7, 0x4f, 0x02, 0x00, 0x00,
}
